name: MyNotinoJobs

on:
  push:
    branches:
      - main

jobs:
  test:
    name: MyNotinoTests
    runs-on: macos-12
    strategy:
      matrix:
        condition: ["$(inherited) SIMULATE_PAGINATION", "$(inherited)"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: 13.2.1
      - name: Install Mint
        run: brew install mint
      - name: Generate Xcode project
        env:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${{ matrix.condition }}
        run: mint bootstrap && mint run xcodegen
      - name: Install Bundler
        run: gem install bundler:2.2.16
      - name: Bundle Install
        run: bundle install
      - name: CocoaPods
        run: bundle exec pod install
      - name: Build and test
        run: xcodebuild test -workspace MyNotino.xcworkspace -scheme MyNotinoApp -destination "platform=iOS Simulator,OS=15.2,name=iPhone 8"
